basePath: /goa-erp
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Account:
    description: system user table (default view)
    example:
      create_date: 1997-09-21T02:28:08Z
      create_uid: 1
      email: 272685110@qq.com
      id: 1
      update_date: 1996-04-03T01:28:34Z
      update_uid: 1
      username: cloudy
    properties:
      create_date:
        description: Date of create
        example: 1997-09-21T02:28:08Z
        format: date-time
        type: string
      create_uid:
        description: account id of create
        example: 1
        format: int64
        type: integer
      email:
        description: email of account
        example: 272685110@qq.com
        format: email
        type: string
      id:
        description: ID of account
        example: 1
        format: int64
        type: integer
      update_date:
        description: Date of update
        example: 1996-04-03T01:28:34Z
        format: date-time
        type: string
      update_uid:
        description: account id of update
        example: 1
        format: int64
        type: integer
      username:
        description: username of account
        example: cloudy
        type: string
    required:
    - id
    - username
    - email
    title: 'Mediatype identifier: application/vnd.account+json; view=default'
    type: object
  AccountCollection:
    description: AccountCollection is the media type for an array of Account (default
      view)
    example:
    - create_date: 1997-09-21T02:28:08Z
      create_uid: 1
      email: 272685110@qq.com
      id: 1
      update_date: 1996-04-03T01:28:34Z
      update_uid: 1
      username: cloudy
    - create_date: 1997-09-21T02:28:08Z
      create_uid: 1
      email: 272685110@qq.com
      id: 1
      update_date: 1996-04-03T01:28:34Z
      update_uid: 1
      username: cloudy
    - create_date: 1997-09-21T02:28:08Z
      create_uid: 1
      email: 272685110@qq.com
      id: 1
      update_date: 1996-04-03T01:28:34Z
      update_uid: 1
      username: cloudy
    items:
      $ref: '#/definitions/Account'
    title: 'Mediatype identifier: application/vnd.account+json; type=collection; view=default'
    type: array
  Company:
    description: system user table (default view)
    example:
      create_date: 1994-08-15T02:47:42Z
      create_uid: 1
      id: 1
      name: 弛菡
      update_date: 1998-01-14T02:43:33Z
      update_uid: 1
    properties:
      create_date:
        description: Date of create
        example: 1994-08-15T02:47:42Z
        format: date-time
        type: string
      create_uid:
        description: company id of create
        example: 1
        format: int64
        type: integer
      id:
        description: ID of company
        example: 1
        format: int64
        type: integer
      name:
        description: name of company
        example: 弛菡
        type: string
      update_date:
        description: Date of update
        example: 1998-01-14T02:43:33Z
        format: date-time
        type: string
      update_uid:
        description: company id of update
        example: 1
        format: int64
        type: integer
    required:
    - id
    - name
    title: 'Mediatype identifier: application/vnd.company+json; view=default'
    type: object
  CompanyCollection:
    description: CompanyCollection is the media type for an array of Company (default
      view)
    example:
    - create_date: 1994-08-15T02:47:42Z
      create_uid: 1
      id: 1
      name: 弛菡
      update_date: 1998-01-14T02:43:33Z
      update_uid: 1
    - create_date: 1994-08-15T02:47:42Z
      create_uid: 1
      id: 1
      name: 弛菡
      update_date: 1998-01-14T02:43:33Z
      update_uid: 1
    - create_date: 1994-08-15T02:47:42Z
      create_uid: 1
      id: 1
      name: 弛菡
      update_date: 1998-01-14T02:43:33Z
      update_uid: 1
    items:
      $ref: '#/definitions/Company'
    title: 'Mediatype identifier: application/vnd.company+json; type=collection; view=default'
    type: array
externalDocs:
  description: golang
  url: https://hexiaoyun128.github.io/cloudy-blog
host: localhost:8081
info:
  contact:
    email: 272685110@qq.com
    name: cloudy
    url: https://hexiaoyun128.github.io/cloudy-blog
  description: 'golang goa-erp use goa '
  license:
    name: MIT
    url: https://hexiaoyun128.github.io/cloudy-blog
  title: golang goa-erp use goa
  version: ""
paths:
  /account:
    get:
      description: list all accounts
      operationId: account#list
      produces:
      - application/vnd.account+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AccountCollection'
      schemes:
      - http
      summary: list account
      tags:
      - account
  /company:
    get:
      description: list all companys
      operationId: company#list
      produces:
      - application/vnd.company+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CompanyCollection'
      schemes:
      - http
      summary: list company
      tags:
      - company
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
